name: Publish NuGet Package
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0

    steps:
      - uses: actions/checkout@v4

      - name: test and publish Lamg.Env
        run: |
          dotnet restore Lamg.Env.slnx
          dotnet build Lamg.Env.slnx -c Release --no-restore
          dotnet run --project Lamg.Env.Tests -c Release --no-build
          dotnet pack Lamg.Env/Lamg.Env.fsproj -c Release --no-build
          dotnet nuget push Lamg.Env/nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
